"""initial schema

Revision ID: 285cb1defc8a
Revises: 
Create Date: 2026-09-03 17:07:15.698091
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '285cb1defc8a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('manager_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_users_active_role', 'users', ['is_active', 'role_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_activity_created', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('project_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), sa.Computed('week_start + INTERVAL 6 DAY', persisted=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'NEEDS_CORRECTION', 'APPROVED', name='reportstatus'), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('first_submitted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_submitted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reviewed_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_reports_user_week'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_reports_user_week', 'reports', ['user_id', 'week_start'], unique=False)
    op.create_index('idx_reports_week_status', 'reports', ['week_start', 'status'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('report_achievements',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('key_guard', mysql.BIGINT(unsigned=True), sa.Computed('IF(is_key, report_id, NULL)', persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_guard', name='uq_achievements_one_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_achievements_report_id'), 'report_achievements', ['report_id'], unique=False)
    op.create_table('report_blockers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='blockerseverity'), nullable=False),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('key_guard', mysql.BIGINT(unsigned=True), sa.Computed('IF(is_key, report_id, NULL)', persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_guard', name='uq_blockers_one_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_blockers_is_resolved'), 'report_blockers', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_report_blockers_report_id'), 'report_blockers', ['report_id'], unique=False)
    op.create_table('report_hours',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('task_type', sa.Enum('DEVELOPMENT', 'TESTING', 'MEETINGS', 'DOCUMENTATION', 'REVIEW', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('hours >= 0', name='ck_hours_positive'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'task_type', name='uq_hours_report_type'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('report_next_week_tasks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_next_week_tasks_report_id'), 'report_next_week_tasks', ['report_id'], unique=False)
    op.create_table('report_tasks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('project_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'DEFERRED', name='taskstatus'), nullable=False),
    sa.Column('planned_pct', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('actual_pct', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('hours_planned', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hours_spent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deliverable', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('actual_pct BETWEEN 0 AND 100', name='ck_tasks_actual'),
    sa.CheckConstraint('hours_planned >= 0 AND hours_spent >= 0', name='ck_tasks_hours'),
    sa.CheckConstraint('planned_pct BETWEEN 0 AND 100', name='ck_tasks_planned'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_tasks_report_id'), 'report_tasks', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_tasks_status'), 'report_tasks', ['status'], unique=False)
    op.create_table('report_versions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('submitted_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version_no', name='uq_versions_report_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_versions_report', 'report_versions', ['report_id', 'version_no'], unique=False)
    op.create_table('review_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('report_version_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reviewer_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REQUEST_CHANGES', name='reviewaction'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.Enum('DRAFT', 'SUBMITTED', 'NEEDS_CORRECTION', 'APPROVED', name='reportstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('DRAFT', 'SUBMITTED', 'NEEDS_CORRECTION', 'APPROVED', name='reportstatus'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_review_report_created', 'review_history', ['report_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_history_report_version_id'), 'review_history', ['report_version_id'], unique=False)
    op.create_index(op.f('ix_review_history_reviewer_id'), 'review_history', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_history_reviewer_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_report_version_id'), table_name='review_history')
    op.drop_index('idx_review_report_created', table_name='review_history')
    op.drop_table('review_history')
    op.drop_index('idx_versions_report', table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_report_tasks_status'), table_name='report_tasks')
    op.drop_index(op.f('ix_report_tasks_report_id'), table_name='report_tasks')
    op.drop_table('report_tasks')
    op.drop_index(op.f('ix_report_next_week_tasks_report_id'), table_name='report_next_week_tasks')
    op.drop_table('report_next_week_tasks')
    op.drop_table('report_hours')
    op.drop_index(op.f('ix_report_blockers_report_id'), table_name='report_blockers')
    op.drop_index(op.f('ix_report_blockers_is_resolved'), table_name='report_blockers')
    op.drop_table('report_blockers')
    op.drop_index(op.f('ix_report_achievements_report_id'), table_name='report_achievements')
    op.drop_table('report_achievements')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index('idx_reports_week_status', table_name='reports')
    op.drop_index('idx_reports_user_week', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index('idx_activity_entity', table_name='activity_logs')
    op.drop_index('idx_activity_created', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_active_role', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
